float4 out vPosition : POSITION;
float3 out FragPos : TEXCOORD0;
float3 out vNormal : TEXCOORD1;
float2 out vTexCoord : TEXCOORD2;

uniform float4x4 mvp;
uniform float4x4 model;
uniform float3x3 modelInverse;

void main(float3 iPosition,float3 iNormal,float2 iTexCoord)
{
	vPosition = mul(float4(iPosition, 1.f),mvp);				
	FragPos = float3(mul(float4(iPosition, 1.f),model));
	vNormal =  mul(iNormal,modelInverse);
	vTexCoord = iTexCoord;
}
